### ISSUE TITLE
Error "‘AVOutputFormat’ does not name a type   AVOutputFormat *of;"

### ISSUE THREAD

**Issue by temple** [ZoneMinder/zoneminder#340]
I work on a Ubuntu Saucy (13.10) x64
I've downloaded ZoneMinder -1.26.5 tarball, satisfied all required dependencies at cmake, and got the source for ffmpeg package.

Cmake compilation ends succesfully; but make crashes with following trace:

In file included from /usr/src/ZoneMinder-1.26.5/src/zm_event.cpp:34:0:
/usr/src/ZoneMinder-1.26.5/src/zm_mpeg.h:44:2: error: ‘AVOutputFormat’ does not name a type
  AVOutputFormat _of;
  ^
/usr/src/ZoneMinder-1.26.5/src/zm_mpeg.h:45:2: error: ‘AVFormatContext’ does not name a type
  AVFormatContext *ofc;
  ^
/usr/src/ZoneMinder-1.26.5/src/zm_mpeg.h:46:2: error: ‘AVStream’ does not name a type
  AVStream *ost;
  ^
make[2]: *_\* [src/CMakeFiles/zm.dir/zm_event.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/zm.dir/all] Error 2
make: **\* [all] Error 2

Any idea or suggestion should be very appreciated.
Thanks in advance
